let priceProducts = document.querySelector(".price-products")
console.log(typeof priceProducts)
console.log(Object.keys(priceProducts))
let product = document.querySelector(".product")
console.log(typeof product)
console.log(Object.entries(product))
let productName = document.querySelector(".product-name")
console.log(typeof productName)
console.log(productName)